# Generated by Django 3.2.11 on 2022-07-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Size'},
        ),
    ]
