# Generated by Django 3.2.11 on 2022-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
