# Generated by Django 3.2.11 on 2022-12-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='discount_price',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productweight',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='ex. kilogram, Pcs, packets.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unitofmeasure'),
        ),
    ]
