# Generated by Django 3.2.11 on 2023-07-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230730_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='ex. kilogram, Pcs, packets.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='ex. 1, 1.5, 2, 5, 10.', max_length=10, null=True, verbose_name='Product Weight'),
        ),
    ]
