# Generated by Django 3.2.11 on 2023-07-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230730_2115'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='product',
    #         name='sizes',
    #         field=models.ForeignKey(blank=True, default=None, help_text='ex. Small, Medium, Large.', on_delete=django.db.models.deletion.CASCADE, to='products.size'),
    #     ),
    # ]
