# Generated by Django 3.2.11 on 2023-07-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
