# Generated by Django 3.2.11 on 2022-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_code', models.CharField(max_length=50, unique=True, verbose_name='Offer Code')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_upto', models.DateTimeField(verbose_name='Valid Upto')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discount (%)')),
                ('max_discount_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Max Discount Amount')),
                ('min_order_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Min Order Amount')),
                ('is_one_time_use', models.BooleanField(blank=True, default=False, null=True, verbose_name='One Time Use')),
                ('is_new_customer', models.BooleanField(blank=True, default=False, null=True, verbose_name='New Customer')),
                ('offer_banner', models.ImageField(upload_to='offer_banner', verbose_name='Offer Banner')),
                ('offer_short_desc', models.CharField(max_length=255, verbose_name='Offer Short Desc')),
                ('offer_full_desc', models.TextField(blank=True, null=True, verbose_name='Offer Full Desc')),
                ('offer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, verbose_name='Offer Status')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
