# Generated by Django 3.2.11 on 2022-10-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walletBalance', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Wallet Balance')),
                ('transactionId', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('trasactionAmt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tnx Amount')),
                ('transactionType', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='credit', max_length=25, verbose_name='Transaction Type')),
                ('orderNumber', models.CharField(blank=True, editable=False, max_length=25, null=True, verbose_name='Order Number')),
                ('razopayPaymentId', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Razor PaymentId')),
                ('razopayOrderId', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Razorpay Order Id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=25, verbose_name='Wallet status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My Wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
