# Generated by Django 3.2.11 on 2022-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_alter_mywallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='trasactionAmt',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Tnx Amount'),
        ),
    ]
