# Generated by Django 3.2.11 on 2022-06-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveryExecutive', '0001_initial'),
        ('products', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Mobile No')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code')),
                ('address_line', models.CharField(help_text='Address (House No, Building, Street, Area)', max_length=255, null=True, verbose_name='Address')),
                ('locality', models.CharField(max_length=255, verbose_name='Locality/Town')),
                ('city', models.CharField(help_text='City/District', max_length=255, verbose_name='City/District')),
                ('state', models.CharField(help_text='State', max_length=255, verbose_name='State')),
                ('save_address_as', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home', max_length=200, verbose_name='Save Address As')),
                ('is_default', models.BooleanField(default=False)),
                ('map_lat', models.CharField(default='0.0', max_length=50, verbose_name='Map Lat')),
                ('map_lng', models.CharField(default='0.0', max_length=50, verbose_name='Map Lng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact Address',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Products Price')),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Shipping Charges')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total Tax')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Grand Total')),
                ('offer_code', models.CharField(blank=True, default='N/A', max_length=20, null=True, verbose_name='Offer Code')),
                ('offer_discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Discount Amount')),
                ('payment_method', models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash On Delivery')], default='COD', max_length=200, null=True, verbose_name='Payment Methods')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50, null=True, verbose_name='Payment Status')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100, verbose_name='Order Status')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ShippingAddress', to='orders.contactaddress')),
                ('delivery_exe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Delivery_executive', to='deliveryExecutive.deliveryexecutive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='VendorOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_items', models.IntegerField(default=0, verbose_name='Total Items')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Total Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Tax')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Grand Total')),
                ('order_status', models.CharField(choices=[('Waiting For Pickup', 'Waiting For Pickup'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered')], default='Waiting for Pickup', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Products Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='orders.orderdetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Order Product Details',
            },
        ),
        migrations.CreateModel(
            name='DeliveryExeLiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_map_lat', models.CharField(max_length=50, verbose_name='Map Lat')),
                ('live_map_lng', models.CharField(max_length=50, verbose_name='Map Lng')),
                ('live_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('intransit', 'In Transit')], default='inactive', max_length=20, verbose_name='Live Status')),
                ('delivery_exe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deliveryExecutive.deliveryexecutive')),
                ('live_oder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail')),
            ],
            options={
                'verbose_name_plural': 'Delivery Exe. Live Data',
            },
        ),
    ]
