# Generated by Django 3.2.11 on 2022-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryexelivedata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Delivery Exe. Live Data'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='orderproductdetail',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order Product Details'},
        ),
        migrations.AlterModelOptions(
            name='vendororderdetails',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vendor Orders'},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash On Delivery'), ('wallet', 'Wallet')], default='COD', max_length=200, null=True, verbose_name='Payment Methods'),
        ),
    ]
