# Generated by Django 3.2.11 on 2022-12-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221214_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductdetail',
            name='userOrderedProductStatus',
        ),
    ]
