# Generated by Django 3.2.11 on 2022-06-02 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pancard', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pan')),
                ('pancard_doc', models.FileField(blank=True, null=True, upload_to='documents/deliveryExecutive/panCard')),
                ('aadhaarcard', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aadhaar')),
                ('aadhaarcard_doc', models.FileField(blank=True, null=True, upload_to='documents/deliveryExecutive/aadhaarCard')),
                ('driving_license', models.CharField(max_length=20)),
                ('driving_license_doc', models.FileField(blank=True, null=True, upload_to='documents/deliveryExecutive/drivingLicense')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Executive',
                'verbose_name_plural': 'Delivery Executives',
                'ordering': ['-status'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryExeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acc_no', models.CharField(max_length=255, verbose_name='Account No')),
                ('acc_ifsc', models.CharField(max_length=255, verbose_name='IFSC Code')),
                ('acc_branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('acc_bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('is_default', models.BooleanField(default=True, verbose_name='Default')),
                ('delivery_exe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deliveryExecutive.deliveryexecutive')),
            ],
            options={
                'verbose_name_plural': 'Delivery Exe. Banks',
            },
        ),
        migrations.CreateModel(
            name='DeliveryExeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='Address (Building No, Street, Area)', max_length=255, null=True, verbose_name='Address')),
                ('locality', models.CharField(max_length=255, verbose_name='Locality/Town')),
                ('city', models.CharField(help_text='City/District', max_length=255, verbose_name='City/District')),
                ('state', models.CharField(help_text='State', max_length=255, verbose_name='State')),
                ('postcode', models.CharField(max_length=50, verbose_name='Post Code')),
                ('map_lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Map Lat')),
                ('map_lng', models.CharField(blank=True, max_length=50, null=True, verbose_name='Map Lng')),
                ('delivery_exe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deliveryExecutive.deliveryexecutive')),
            ],
            options={
                'verbose_name_plural': 'Delivery Exe. Address',
            },
        ),
    ]
