# Generated by Django 3.2.11 on 2022-12-23 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220701_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Account Holder Name')),
                ('acc_no', models.CharField(max_length=255, verbose_name='Account No')),
                ('acc_ifsc', models.CharField(max_length=255, verbose_name='IFSC Code')),
                ('acc_branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('acc_bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('branchCode', models.CharField(max_length=20, verbose_name='Branch Code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
